### PR TITLE
ConsumerAction for API + fix Importer + addLegacyLine for "&" colors

### PR DESCRIPTION
**Pull request by EternalHuman**
Why is there no ConsumerAction in API?

addTextLine broken with "§" symbol. (Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information.)

### CODE REVIEW

**Comment by Pyrbu** [comment]
>Why is there no ConsumerAction in API?

You mean like an interaction action that just runs a runnable? That isn't a thing because we have no way of serializing them to save them but I guess we can add it just without the possibility of saving. Although you can probably already achieve anything you want with the `NpcInteractEvent`

> addTextLine broken with "§" symbol.

Literally just don't use it, the current system is designed to work with legacy codes (&) already, just switch all of them out, also your `Component.text()` solution wouldn't work anyways since that is still constructing a component with the section character which would give you the exact same error back.

**Comment by EternalHuman** [comment]
> > Why is there no ConsumerAction in API?
> 
> You mean like an interaction action that just runs a runnable? That isn't a thing because we have no way of serializing them to save them but I guess we can add it just without the possibility of saving. Although you can probably already achieve anything you want with the `NpcInteractEvent`
> 
> > addTextLine broken with "§" symbol.
> 
> Literally just don't use it, the current system is designed to work with legacy codes (&) already, just switch all of them out, also your `Component.text()` solution wouldn't work anyways since that is still constructing a component with the section character which would give you the exact same error back.

I already use NpcInteractEvent but it's not as effective as ConsumerAction.

**Comment by EternalHuman** [comment]
"That isn't a thing because we have no way of serializing them to save them but I guess we can add it just without the possibility of saving"
image
This is already supported in your plugin

**Comment by EternalHuman** [comment]
image

**Comment by Pyrbu** [comment]
> "That isn't a thing because we have no way of serializing them to save them but I guess we can add it just without the possibility of saving" image This is already supported in your plugin

Just because there's failsafes for it doesn't mean that it's supported

**Comment by EternalHuman** [comment]
now it's supported

**Comment by EternalHuman** [comment]
> > Why is there no ConsumerAction in API?
> 
> You mean like an interaction action that just runs a runnable? That isn't a thing because we have no way of serializing them to save them but I guess we can add it just without the possibility of saving. Although you can probably already achieve anything you want with the `NpcInteractEvent`
> 
> > addTextLine broken with "§" symbol.
> 
> Literally just don't use it, the current system is designed to work with legacy codes (&) already, just switch all of them out, also your `Component.text()` solution wouldn't work anyways since that is still constructing a component with the section character which would give you the exact same error back.

I can't "don't use it". After update with MiniMessage i have to use " this.npc.getHologram().addLine(customNPCType.getName().replace("§", "&"));" and this is very bad. Expand API or just merge my PR...

**Comment by Pyrbu** [comment]
I already told you that what you wrote won't work anyways since you're still putting the section character into a component

**Comment by EternalHuman** [comment]
I don't want to use my fork. I want to improve the original plugin and use it.

**Comment by EternalHuman** [comment]
> I already told you that what you wrote won't work anyways since you're still putting the section character into a component

It works.

**Comment by EternalHuman** [comment]
U can test it

**Comment by EternalHuman** [comment]
The symbol "§" is still used even on the latest versions, and your api literally does not allow it to be used. My version solves all the problems.

**Comment by EternalHuman** [comment]
image
this.npc.getHologram().addLine(customNPCType.getName());
As you can see it works with my PR

**Comment by EternalHuman** [comment]
I will use my fork. Close the pull request.

**Pull request closed without merging**
