### PR TITLE
Upgrade packetevents

### PR DESCRIPTION
**Pull request by NoltoxGit**
Hello,
Here's an update with some dependencies updated and in particular PacketsEvents who have released an update that fixes the problem from last time due to downgrade.

### CODE REVIEW

**Comment by Pyrbu** [comment]
I'm pretty sure you also need to update all of these if you're updating adventure
image

**Comment by NoltoxGit** [comment]
> I'm pretty sure you also need to update all of these if you're updating adventure image

Done ! :)

**Comment by Pyrbu** [comment]
Also have you tested this on 1.20.2/1.19.4? I'm pretty sure most of the people that were having the issue were using those versions.

**Comment by NoltoxGit** [comment]
> Also have you tested this on 1.20.2/1.19.4? I'm pretty sure most of the people that were having the issue were using those versions.

Idk because I can't compile the plugin on my pc with `gradle build` or any other command :/

**Pull request merged**
