### PR TITLE
Add passengers to npc api

### PR DESCRIPTION
**Pull request by AshleyThew**
Add passengers to npc api & implementation
Add jetbrains annotations to api to tag with nullables

### CODE REVIEW

**Comment by AshleyThew** [comment]
Also fixed the edit for switchserver which I randomly stumbled across

**Comment by AshleyThew** [comment]
Added vehicles by entity id for cases where the entity is an existing server npc

**Comment by D3v1s0m** [comment]
This looks good and seems to be working (didn't break anything). But have you tested the API itself?
Because for the plugin, the npc's location is still the same, and if the API uses setVehicleId on some real entity which can move, there cause be issue with npc despawning.

If you have tested the API, we can merge it.

**Comment by AshleyThew** [comment]
My understanding would be that the plugin using the api would have to keeping track of moving both the real entity and the npc since its more of api point than a command/setting.

**Comment by AshleyThew** [comment]
As for the specific question, no I have not been able to test it specifically, still working on an implementation.
Have yet to be able to compile, porting over from another plugin and adding missing features as I find them.

**Pull request merged**
